### ISSUE TITLE
Add GitHub add-on

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/infrastructure-templates#61]
## Why

- We haven't added `.github` folder to the generated project.
- We need to add:
  - [git-template](https://github.com/nimblehq/git-template/tree/main/.github) to have issue/pull requests template
  - `linting` workflow. The workflow could be the following code:

```
name: Linting

on: pull_request

env:
  TERRAFORM_VERSION: "1.2.4"

jobs:
  linting:
    name: Linting

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Run Terraform format
        run: terraform fmt -recursive -check
```

## Who Benefits?

Developer
